### ISSUE TITLE
Minifying with ESBuildMinifyPlugin breaks source maps

### ISSUE THREAD

**Issue by matthewtusker** [privatenumber/esbuild-loader#289] opened 2022-12-15 12:15 UTC
### Bug description

While adding `esbuild-loader` to a project I encountered an issue with source maps returned after minification:

```
Error while fetching an original source: can't assign to property "metadata" on "unsupported protocol for sourcemap request webpack:///index.ts": not an object
Source URL: <unknown>
```
![image](https://user-images.githubusercontent.com/116569994/207856067-f9bf9d9c-a751-4502-b16e-eecfbd90372f.png)

Disabling minification returns the builds to producing usable sourcemaps again. Note that we aren't using Typescript in out project (though I'm aware that esbuild uses it under the hood).

### Reproduction

Use the following minimizer options:
```
    minimizer: [
      new ESBuildMinifyPlugin({
        target: 'esnext',
        css: true,
      }),
    ],
```

### Node.js package manager

yarn

### Environment

```shell
System:
    OS: macOS 13.0.1
    CPU: (10) arm64 Apple M1 Pro
    Memory: 799.66 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 14.20.1 - ~/.asdf/installs/nodejs/14.20.1/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 6.14.17 - ~/.asdf/plugins/nodejs/shims/npm
  npmPackages:
    esbuild-loader: ^2.20.0 => 2.20.0
    webpack: ^5.74.0 => 5.74.0
```

### Can you contribute a fix?

- [ ] I’m interested in opening a pull request for this issue.

**Comment by privatenumber** [comment] 2022-12-15 13:33
I can't reproduce your problem. And your formatting is broken and difficult to read.

Closing until minimal reproduction is provided.

**Closed as completed by privatenumber** 2022-12-15 13:33 UTC
Labels: bug, pending triage
