### ISSUE TITLE
externals don't work?

### ISSUE THREAD

**Issue by ComLock** [privatenumber/esbuild-loader#101] opened 2021-02-05 14:51 UTC
It seem react becomes bundled even though I write:
externals: {
	react: 'React',
	'react-dom': 'ReactDOM'
}

Anyone got externals to work?

**Comment by privatenumber** [comment] 2021-02-05 14:56
Going to close this since it's not a esbuild-loader question but just a Webpack question.

----

Happy to continue to help though:

Where are you writing that? Do you mind sharing a minimal version of your entire Webpack config?

[externals](https://webpack.js.org/configuration/externals/) should be passed into Webpack as a root level property, and the object syntax means it will be fetched from the global (you must provide React as a global variable `React` before your distribution loads).

**Closed as completed by privatenumber** 2021-02-05 14:56 UTC

**Comment by ComLock** [comment] 2021-02-08 10:20
Here is the webpack config.

```
const MODE = 'development';
const ES_BUILD_TARGET = 'es2015';
{
		context: path.join(__dirname, SRC_ASSETS_DIR),
		entry: {
			'js/react/Collector': './js/react/Collector.jsx'
		},
		//externals: ['react', 'react-dom'],
		externals: {
			react: 'React',
			'react-dom': 'ReactDOM'
		},
		mode: MODE,
		module: {
			rules: [{
				exclude: [
          [
            path.resolve(__dirname, 'node_modules')
					]
				],
				test: /\.jsx$/,
				loader: 'esbuild-loader',
				options: {
					loader: 'jsx', // Remove this if you're not using JSX
					target: ES_BUILD_TARGET
				}
			}]
		}, // module
		optimization: {
			minimize: MODE === 'production',
			minimizer: MODE === 'development'
				? []
				: [
					new ESBuildMinifyPlugin({
						target: ES_BUILD_TARGET
					})
				]
		},
		output: {
			filename: '[name].esm.js',
			library: 'LIB',
			libraryTarget: 'var', // variable defined in root scope
			path: path.join(__dirname, DST_ASSETS_DIR)
		},
		performance: {
			hints: false
		},
		plugins: [
			new ESBuildPlugin(),
			//new EsmWebpackPlugin()
    ],
		resolve: {
			extensions: ['mjs', 'jsx', 'esm', 'es', 'es6', 'js', 'json'].map(ext => `.${ext}`)
		}
	}
```

You can read about esbuild relation to external here:
https://esbuild.github.io/api/#external

I don't know how to make a webpack-loader, so I was just thinking that when you make a webpack-loader you would have to translate a webpack config into an --external flag on the esbuild command line, and that maybe that was missing. Both webpack and esbuild can do bundling, right? Which one actually does it? Also I guess it would be a waste for esbuild to make a huge bundle and then for webpack to threeshake it afterwards. (a lot of wasted cpu cycles) Wouldn't it be better for esbuild to make as small bundle as possible, before giving it back to webpack. I have no idea how this works, I'm only guessing. But I'm happy to learn, if you have the time to explain a little bit.

**Comment by ComLock** [comment] 2021-02-08 12:59
But then again maybe you have not even enabled bundling for esbuild https://esbuild.github.io/api/#bundle

**Comment by privatenumber** [comment] 2021-02-08 23:40
Esbuild has a bundling API and a transform API.

The bundling API works like Webpack, and that's where `external` exists (behaves like Webpack's). esbuild-loader is using the transform API, which doesn't have `external` because it doesn't do any bundling.

I can't see your issue based on that config. Do you have a minimal reproduction repo? I'll be happy to take a look.
