### ISSUE TITLE
minimize: true not working?

### ISSUE THREAD

**Issue by pavelloz** [privatenumber/esbuild-loader#129] opened 2021-03-17 12:20 UTC
## Bug description

I noticed that javascripts are not minimized in production build after switching either from Terser, or from esbuild-loader 2.9.2 (i upgraded to remove deprecation warning).

<details>
<img width="806" alt="image" src="https://user-images.githubusercontent.com/546845/111466344-761ab900-8723-11eb-9539-e423d16c25dd.png">
</details> 

Im 100% sure Terser was minimizing it correctly, im just not sure if older esbuild-loader was or not and i didnt notice.

## Environment

- esbuild-loader version: 2.10.0
- Webpack version: 5.26.2
- Operating System: macos, linux
- Node version: 14
- Package manager (npm/yarn/pnpm) and version: npm 7.6.3

Webpack config:

```
const { ESBuildMinifyPlugin } = require('esbuild-loader');
```

```
      {
        test: /\.js$/,
        loader: 'esbuild-loader',
        options: {
          target: 'es2015',
        },
      },
```

```
  optimization: {
    minimize: true,
    minimizer: [
      new ESBuildMinifyPlugin({
        target: 'es2015',
      }),
    ],
  },
```

**Comment by pavelloz** [comment] 2021-03-17 12:23
I just commented out whole `optimization` hash to make default webpack minimize and it correctly minimizes js files. Its just slower.

<details>
<img width="1131" alt="image" src="https://user-images.githubusercontent.com/546845/111466781-fc36ff80-8723-11eb-8dcb-b02ee7a70ece.png">
</details>

**Comment by privatenumber** [comment] 2021-03-17 16:44
Working fine with v2.10.0 [here](https://github.com/privatenumber/esbuild-loader-examples/tree/master/examples/basic-setup)

Can you provide a minimal reproduction repo? I can try debugging

**Comment by pavelloz** [comment] 2021-03-18 12:54
Sure: https://github.com/pavelloz/esbuild-min

I hope this is minimal enough

This should show what i mean:

```
npm i
npm run build
head -n 20 app/assets/js/app.js
```

**Comment by privatenumber** [comment] 2021-03-18 19:08
It's happening because you output your distribution files with a query in the name:
https://github.com/pavelloz/esbuild-min/blob/837f767093ed453bc6b5841ab447cd616ed176e7/webpack.config.js#L13

Since it's no longer a `.js` file, it's not being acknowledged as a JS file and hence not minified.

This is unconventional and will give you further unexpected behavior. Query params are for attaching data when requesting a file—usually handled by the server—, not for when statically creating one. That said, creating a file called `js/code.js?v=1` vs making a request to `js/code.js?v=1` are completely different. When "queries" are in the filename, it must be URL encoded (eg. `js/code.js%3Fv%3D1`), otherwise it will go to a file called `code.js` (think about how you're going to attach additional query params to this file when requesting it).


Closing as this is not an issue with esbuild-loader.

**Closed as completed by privatenumber** 2021-03-18 19:08 UTC
Labels: needs reproduction

**Comment by pavelloz** [comment] 2021-03-18 19:26
Well, a lot of people add query params for cache busting. Recognizing file extension should not be `.js$` (https://github.com/privatenumber/esbuild-loader/blob/develop/src/minify-plugin.ts#L35). Probably regexp is not needed at all, after inspecting terser source: https://github.com/webpack-contrib/terser-webpack-plugin/blob/master/src/index.js#L638-L640


All other plugins, built into webpack, external, understand that it is javascript if it has `.js` as last extension. This is the first one that ive ever seen anybody claiming it is not. And i had no issues with any plugin for the past 5 years of using it, so im pretty sure they wont arise now. 

If you think this is not issue with esbuild-loader (implying that support in all other loaders/minifiers is wrong) i wish you a good luck in your journey. Ill fork and fix the regexp myself for my own use.

**Comment by privatenumber** [comment] 2021-03-18 19:47
I think you're conflating two different cache-busting techniques:

1. Including a hash in the file name (eg. `file.[hash].js`)
  This works because the output path actually changed from A to B, and is what's recommended by [Webpack: Caching docs](https://webpack.js.org/guides/caching/).


2. Appending a query param after the URL (eg. `https://site.com/file.js?hash`)
  In this case, the file path doesn't actually change. You're forcing the browser to cache-bust by taking advantage of the fact that the browser doesn't know it's a static file and assumes adding a query param will yield a different response. This is not the same as actually naming your file `file.js?hash`.


With your configuration, your build outputs a file like `file.js?v=hashA`, which is `file.js%3Fv%3DhashA` when [URL encoded](https://www.w3schools.com/tags/ref_urlencode.ASP). So, when you want to access it in the browser, you'd be requesting `https://site.com/file.js%3Fv%3DhashA`, and when you want to add query params to it, it would become `https://site.com/file.js%3Fv%3DhashA?query=params`. I don't believe this is a convention or something you actually want.

In the file-system, query params don't exist. It's handled by whatever is processing the request, so it doesn't really make sense to acknowledge and parse query params in a file name.


I'm genuinely curious which processors support this behavior and why they do it. Do you mind linking references?

Edit: I see you edited your comment to include a Terser reference -- thanks. I will look into it. You mentioned other processors support this too?

Edit 2: Looks like Vue.js [allows this too](https://github.com/vuejs/vue/blob/529016bca92f6f098e903b1f77c70d3b0dadefaa/packages/vue-server-renderer/client-plugin.js#L5)

Edit 3: Webpack output supports [`[query]`](https://webpack.js.org/configuration/output/#outputsourcemapfilename), which I think is the same thing as this.

**Comment by rowanoulton** [comment] 2021-04-12 23:00
We, too, would love to switch to esbuild-loader for minification but use query strings as a way of managing our service worker cache. @privatenumber would you accept a PR to amend the regular expression @pavelloz mentioned?

**Comment by privatenumber** [comment] 2021-04-12 23:15
@rowanoulton I'd like to better understand the use-case first. Surprisingly, I see other plugins supporting it, but I couldn't find any explanations as to why.

Do you mind opening a new ticket for it that references this?

**Comment by rowanoulton** [comment] 2021-04-12 23:54
@privatenumber done! https://github.com/privatenumber/esbuild-loader/issues/144

**Comment by rowanoulton** [comment] 2021-04-12 23:55
(... and thank you for the extremely quick replies!)
