### ISSUE TITLE
Treeshaking not working when using esbuild as a loader

### ISSUE THREAD

**Issue by Nikki1993** [privatenumber/esbuild-loader#178] opened 2021-05-25 14:12 UTC
## Bug description

There seems to be a problem with `esbuild-loader` where it doesn't treeshake packages marked as side effects free, like for example Font Awesome.

## Reproduction
I've created a minimal repo to demonstrate the issue using fontawesome package and react https://github.com/Nikki1993/esbuild-loader-treeshaking-issue

It has 2 scripts
- esbuild. will generate the bundle into `esbuild_dist` using native `esbuild`
- webpack. will generate the bundle  into `webpack_dist` using webpack with `esbuild-loader` for `jsx` files. 

Once you generate the bundle you will notice a drastic difference in bundle size

- webpack: main.js **1.25 MiB**
- esbuild: main.js  **297.9kb**

once inspected you will notice that webpack version contains entire icon set of fontawesome where usbuild has it tree shaken and removed. 

## Environment

- esbuild-loader version: 2.13.1
- Webpack version: 5.37.1
- Operating System: MacOS Big Sur 11.4
- Node version: 16.2.0
- Package manager (npm/yarn/pnpm) and version: npm 7.13.0

**Comment by Nikki1993** [comment] 2021-05-25 14:27
[bundle_buddy_analysis.zip](https://github.com/privatenumber/esbuild-loader/files/6540019/bundle_buddy_analysis.zip)

Adding Bundle Buddy analysis zip file that contains both builds and their node_modules contents that you can check here https://www.bundle-buddy.com/ 

or alternatively pushed the code changes to repo above to generate those `meta.json` files that you can then inspect and upload to the tool yourself. 

Hope this helps to further narrow down the issue.

**Comment by privatenumber** [comment] 2021-05-25 17:37
Thanks for the detailed issue @Nikki1993 !

Sadly this is expected behavior and not actually relevant to esbuild-loader.

Webpack [relies on Terser to handle dead code elimination](https://webpack.js.org/guides/tree-shaking/#:~:text=usedexports%20relies%20on%20terser%20to%20detect%20side%20effects%20in%20statements.%20it%20is%20a%20difficult%20task%20in%20javascript%20and%20not%20as%20effective%20as%20straightforward%20sideeffects%20flag.). So, reverting `ESBuildMinifyPlugin` to let Webpack use the default Terser minifier removes the unused code.

esbuild's minification only does dead code elimination in bundle mode and for [top-level variables](https://github.com/evanw/esbuild/issues/639#:~:text=esbuild%20currently%20only%20removes%20unused%20functions%20and%20variables%20at%20the%20top%20level). Neither conditions are met because we can only use the transform API and Webpack wraps the distribution in a iife.

Closing since there's nothing that can be done on esbuild-loader's end but I'll mention this scenario in the esbuild repo.

**Closed as completed by privatenumber** 2021-05-25 17:37 UTC

**Comment by Nikki1993** [comment] 2021-05-25 20:00
Thank you for providing clarification on the matter, indeed I totally missed that `terser` mention in the docs (which totally should have been highlighted imho) and thank you for pushing the word forward in `esbuild` repo.
