### ISSUE TITLE
This loader is not working with absolute paths.

### ISSUE THREAD

**Issue by maksym-nezhurin** [privatenumber/esbuild-loader#269] opened 2022-08-10 13:52 UTC
### Bug description

I try to use this loader in scope of WebPack configuration right now, but as fact that I have a very big project and around all files we are using absolute paths, when I try to make a build a get more than 359 errors related to the path.
I can't find the ability to add some configuration or additional plugin. But the way to update each file is a little bit crazy for me. )

### Reproduction

Use absolute files in your project

### Node.js package manager

yarn

### Environment

```shell
Node: v14.17.0
NPM: 8.6.0
Webpack: 5.62.1
```

### Can you contribute a fix?

- [ ] I’m interested in opening a pull request for this issue.

**Comment by privatenumber** [comment] 2022-08-10 17:36
Sounds like a Webpack misconfiguration problem rather than a esbuild-loader problem.

Please provide a minimal reproduction of the problem so others can help investigate.

**Comment by maksym-nezhurin** [comment] 2022-08-11 08:01
Yeah, I also think so. But it was working before I replaced the loader (from babel to esbuild).
There is my configuration of 3 main files that is responsible for bundling.
Maybe, I have to add some additional plugin or replace 'module-resolver' that is responsible for the path (as I understand).

**Comment by privatenumber** [comment] 2022-08-11 14:11
Closing this out since there doesn't seem to be a bug.

Happy to re-open once a minimal (no irrelevant code) reproduction is provided.

**Closed as completed by privatenumber** 2022-08-11 14:11 UTC
Labels: bug, pending triage

**Comment by maksym-nezhurin** [comment] 2022-08-11 15:08
@privatenumber okay.
But do you know how I can use absolute paths with this [esbuild-loader](https://github.com/privatenumber/esbuild-loader)?
It could be a popular question.
Thank you in advance!

**Comment by privatenumber** [comment] 2022-08-11 15:28
I don't really understand your question. esbuild-loader doesn't do any path resolution—it's all handled by Webpack.

Sounds like you're seeking generic Webpack loader configuration help, and if so, you might want to ask in Webpack Discussions.

FYI This is why a minimal reproduction helps so much. It clearly communicates the problem without needing to describe it accurately.

**Comment by maksym-nezhurin** [comment] 2022-08-12 07:30
Okay! Thank you!
