### ISSUE TITLE
Global scope issue with minified variables

### ISSUE THREAD

**Issue by dartess** [privatenumber/esbuild-loader#292] opened 2022-12-29 11:16 UTC
### Bug description

Hi, thank you for your work! 

I tried using it for minification and encountered a problem: some of the minified variables are ending up in the global scope and since there is no uniqueness between them, a variable from one chunk can overwrite a variable from another chunk. As a result, my code is broken. Is it possible to improve the minification? Or is this an issue with esbuild?

If it matters, I only used the minifier, I didn't use the package as a loader.

### Reproduction

It's hard to reproduce; perhaps the problem fired because I have a fairly large project.

For now, here are examples of problematic code:

(code was formatted after minification)

(fragments of the beginnings of files are given)

`6934.a34d849b35a2dc56b39d.js`

```js
"use strict";
var Ue = Object.defineProperty, We = Object.defineProperties;
var Ve = Object.getOwnPropertyDescriptors;
var fe = Object.getOwnPropertySymbols;
var Le = Object.prototype.hasOwnProperty, Be = Object.prototype.propertyIsEnumerable;
var Oe = (d, r, e) => r in d ? Ue(d, r, { enumerable: !0, configurable: !0, writable: !0, value: e }) : d[r] = e,
  Y = (d, r) => {
    for (var e in r || (r = {})) Le.call(r, e) && Oe(d, e, r[e]);
    if (fe) for (var e of fe(r)) Be.call(r, e) && Oe(d, e, r[e]);
    return d;
  }, me = (d, r) => We(d, Ve(r)); // <----- me#1
var ve = (d, r) => {
  var e = {};
  for (var n in d) Le.call(d, n) && r.indexOf(n) < 0 && (e[n] = d[n]);
  if (d != null && fe) for (var n of fe(d)) r.indexOf(n) < 0 && Be.call(d, n) && (e[n] = d[n]);
  return e;
};
(self.webpackChunk = self.webpackChunk || []).push([[6934], {
  16476: (d, r, e) => {
<...>
```

`3138.ba663efaf5d39ed39ea1.js`:

```js
"use strict";
var Ce = Object.defineProperty, Pe = Object.defineProperties;
var he = Object.getOwnPropertyDescriptors;
var ae = Object.getOwnPropertySymbols;
var de = Object.prototype.hasOwnProperty, ue = Object.prototype.propertyIsEnumerable;
var ce = (E, d, t) => d in E ? Ce(E, d, { enumerable: !0, configurable: !0, writable: !0, value: t }) : E[d] = t,
  te = (E, d) => {
    for (var t in d || (d = {})) de.call(d, t) && ce(E, t, d[t]);
    if (ae) for (var t of ae(d)) ue.call(d, t) && ce(E, t, d[t]);
    return E;
  }, ne = (E, d) => Pe(E, he(d));
var me = (E, d) => { // <----- me#2
  var t = {};
  for (var e in E) de.call(E, e) && d.indexOf(e) < 0 && (t[e] = E[e]);
  if (E != null && ae) for (var e of ae(E)) d.indexOf(e) < 0 && ue.call(E, e) && (t[e] = E[e]);
  return t;
};
(self.webpackChunk = self.webpackChunk || []).push([[3138], {
  40694: (E, d, t) => {
<...>
```

since the variable is global, it is overwritten and I get something like this:

```
TypeError: d.indexOf is not a function
```

### Node.js package manager

npm

### Environment

```shell
System:
    OS: macOS 13.0
    CPU: (10) arm64 Apple M1 Pro
    Memory: 814.23 MB / 32.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.12.0 - /usr/local/bin/node
    Yarn: 1.22.18 - /usr/local/bin/yarn
    npm: 8.19.2 - /usr/local/bin/npm
  npmPackages:
    esbuild-loader: ^2.20.0 => 2.20.0 
    webpack: ^5.53.0 => 5.74.0
```

### Can you contribute a fix?

- [ ] I’m interested in opening a pull request for this issue.

**Comment by privatenumber** [comment] 2022-12-29 14:11
Closing as duplicate of https://github.com/privatenumber/esbuild-loader/issues/139

**Closed as completed by privatenumber** 2022-12-29 14:11 UTC
Labels: bug, pending triage
