### ISSUE TITLE
Typescript compiler error: The character ">" is not valid inside a JSX element

### ISSUE THREAD

**Issue by dryzhkov** [privatenumber/esbuild-loader#314] opened 2023-02-10 22:36 UTC
### Bug description

After upgrading to V3, TS complier starts mistakenly transpiling generics in .ts files as JSX elements.

Broken on:
esbuild-loader: v3.0.0 
esbuild: v0.17.6
typescript: v4.7.4

Worked as expected on: 
esbuild-loader: v2.21.0
esbuild: v0.16.17
typescript: v4.7.4

### Reproduction

You can repro this issue by using the [code sample](https://www.typescriptlang.org/play?ts=4.7.4#code/MYewdgzgLgBADgJxAWwJYQKYQIIBtcDKGUUuGAJjALwwA8AKgHwAUiK6WAXDAApJqYGjANoBdAJTc+7QQCUArmDy5sEAJ5hgsrPNxRa0gRiEAaGE0bVGAKBgwEi5ao3BW-DhDNwr8cQG4gA)  - toggle JSX from "React" to "None" in tsconfig options

### Node.js package manager

npm

### Environment

```shell
esbuild-loader: v3.0.0 
esbuild: v0.17.6
typescript: v4.7.4
```

### Can you contribute a fix?

- [ ] I’m interested in opening a pull request for this issue.

**Comment by privatenumber** [comment] 2023-02-10 22:42
I can't help you with how little information you've provided.

Closing until a minimal reproduction is provided.

**Comment by dryzhkov** [comment] 2023-02-10 22:43
Do you mind telling me what additional information your require to repro this?

**Closed as completed by privatenumber** 2023-02-10 22:42 UTC

**Comment by privatenumber** [comment] 2023-02-10 22:44
Link to a repository with _only_ the relevant files. The reproduction should be _minimal_.

I should be able to see the error in my console when I run `npm start`.

Tip: Look at it from my point of view. If you're solicited help from a stranger online (zero context), what information would you need?

**Comment by dryzhkov** [comment] 2023-02-10 23:40
Tip: if you want people to submit bugs with more context consider providing a boilerplate repo to save them time.

BTW, the bug report does contain context. I provided you with exact package versions of all necessary dependencies and source code that causes the issue. As well as the steps that I have taken.

**Comment by privatenumber** [comment] 2023-02-10 23:42
I already did, it's in the bug report template. There's also https://github.com/privatenumber/esbuild-loader-examples

Sorry but no one is going to spend time setting that up only to find that there's no bug and it's a mistake in your config. If you want free help from strangers, you'll have to put in a lot more work.

**Comment by dryzhkov** [comment] 2023-02-11 00:55
Here is [a repro](https://stackblitz.com/edit/node-msv1ej?file=webpack.config.js,src%2Fts.ts&view=editor)

**Comment by privatenumber** [comment] 2023-02-11 01:00
Thanks for the reproduction. But yeah, looks like a bug in your configuration; check out the migration guide. You also have a syntax error.

**Comment by dryzhkov** [comment] 2023-02-11 01:11
Can you be a little bit more specific what is the configuration bug?

**Comment by evanw** [comment] 2023-02-11 01:32
[You cannot use the `tsx` loader for `*.ts` files.](https://esbuild.github.io/content-types/#ts-vs-tsx) I'm guessing that you can just remove the incorrect configuration value to fix your problem:

```diff
 module: {
   rules: [
     {
       test: /\.[tj]sx?$/,
       loader: 'esbuild-loader',
       options: {
         target: 'es2015',
-        loader: 'tsx', // Or 'ts' if you don't need tsx
         target: 'es2018',
         jsx: 'automatic',
       },
     },
   ],
 },
```

**Comment by privatenumber** [comment] 2023-02-11 11:01
I've updated the migration guide to make that clearer.
